name: TyperAI

options:
  bundleIdPrefix: com.typer
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    PRODUCT_NAME: Typer
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    ENABLE_HARDENED_RUNTIME: YES
    SWIFT_STRICT_CONCURRENCY: minimal
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

targets:
  TyperAI:
    type: application
    platform: macOS
    bundleId: com.typer.mac
    deploymentTarget: "14.0"
    sources:
      - TyperAI
    info:
      path: TyperAI/Info.plist
      properties:
        LSUIElement: true
        NSPrincipalClass: NSApplication
        CFBundleName: Typer
        CFBundleDisplayName: Typer®
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSHighResolutionCapable: true
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    entitlements:
      path: TyperAI/TyperAI.entitlements
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: YES
        CODE_SIGN_ENTITLEMENTS: TyperAI/TyperAI.entitlements
